blank_issues_enabled: false
contact_links:
  - name: Omar Samir
    url: https://twitter.com/o___samir/
    des: Send Us a Message On Twitter For Now, Sorry For That But We Will Fix The Contact Issue As Soon As Possible 
    about: Please ask and answer questions here.
  - name: Random Projects Bug and New Features Should Be Posed Here 
   
