blank_issues_enabled: false
contact_links:
  - name: Omar Samir
    url: https://github.com/Omsamiir
    about: Please ask and answer questions here.
  - name: Random Projects Bug and New Features Should Be Posed Here 
   
