blank_issues_enabled: false
contact_links:
  - name: Omar Samir
    url: https://twitter.com/messages/1301567222742122497-1474542376182071297
    about: Please ask and answer questions here.
  - name: Random Projects Bug and New Features Should Be Posed Here 
   
